version: '3'
services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: mg
    ports:
      - 27017:27017
      
  postgres:
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: mg
      POSTGRES_PASSWORD: mg
      POSTGRES_DB: mg-wsb

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
