version: '3'
services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: licencjat
    ports:
      - 27017:27017
      
  postgres:
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: licencjat
      POSTGRES_PASSWORD: licencjat
      POSTGRES_DB: licencjat-ug

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080